![Hand with calculator](calculator.png "Calculator")

Did you know that the average return from investing in stocks is 10% per year! But who wants to be average?! 

You have been asked to support an investment firm by analyzing trends in high-growth companies. They are interested in understanding which industries are producing the highest valuations and the rate at which new high-value companies are emerging. Providing them with this information gives them a competitive insight as to industry trends and how they should structure their portfolio looking forward.

You have been given access to their `unicorns` database, which contains the following tables:

`dates`
| Column       | Description                                  |
|------------- |--------------------------------------------- |
| company_id   | A unique ID for the company.                 |
| date_joined  | The date that the company became a unicorn.  |
| year_founded | The year that the company was founded.       |

`funding`
| Column           | Description                                  |
|----------------- |--------------------------------------------- |
| company_id       | A unique ID for the company.                 |
| valuation        | Company value in US dollars.                 |
| funding          | The amount of funding raised in US dollars.  |
| select_investors | A list of key investors in the company.      |

`industries`
| Column       | Description                                  |
|------------- |--------------------------------------------- |
| company_id   | A unique ID for the company.                 |
| industry     | The industry that the company operates in.   |

`companies`
| Column       | Description                                       |
|------------- |-------------------------------------------------- |
| company_id   | A unique ID for the company.                      |
| company      | The name of the company.                          |
| city         | The city where the company is headquartered.      |
| country      | The country where the company is headquartered.   |
| continent    | The continent where the company is headquartered. |

In [11]:
SELECT industry, unicorn_year as year, COUNT(company) AS num_unicorns, 
ROUND(AVG(valuation)/1000000000,2) as average_valuation_billions
FROM companies
LEFT JOIN industries
USING (company_id)
LEFT JOIN funding
USING (company_id)
INNER JOIN (SELECT * FROM (SELECT *,EXTRACT(YEAR FROM date_joined) AS                     unicorn_year FROM dates) AS a
          WHERE unicorn_year IN (2019,2020,2021)) AS p
USING (company_id)
WHERE industry IN (SELECT industry FROM(SELECT industry, COUNT(company) AS                         num_unicorns
                    FROM companies
                    LEFT JOIN industries
                    USING (company_id)
                    INNER JOIN (SELECT * FROM (SELECT *,EXTRACT(YEAR FROM                           date_joined) AS unicorn_year FROM dates) AS a
                    WHERE unicorn_year IN (2019,2020,2021)) AS p
                    USING (company_id)
                    GROUP BY industry
                    ORDER BY num_unicorns DESC
                    LIMIT 3) as b)
GROUP BY industry, year
ORDER BY industry, year DESC

                          industry  ...  average_valuation_billions
0  E-commerce & direct-to-consumer  ...                        2.47
1  E-commerce & direct-to-consumer  ...                        4.00
2  E-commerce & direct-to-consumer  ...                        2.58
3                          Fintech  ...                        2.75
4                          Fintech  ...                        4.33
5                          Fintech  ...                        6.80
6     Internet software & services  ...                        2.15
7     Internet software & services  ...                        4.35
8     Internet software & services  ...                        4.23

[9 rows x 4 columns]